# information for application name and launcher
app-builder: 1e817d6

Application:

  name: IgnisStamp
  asciibanner: assets/banner.txt
  icon: assets/IgnisStamp.svg.ico
  installdir: '%localappdata%\Ignis\IgnisStamp'

  # After installation
  pause: 1

  programdata:
    - [ ./bin, ./bin ]
    - [ ./assets, ./assets ]
    - [ ./scripts, ./scripts ]
    - [ ./documents, ./documents ]


# Download Python/R (optional) and their dependencies to be deployed
Dependencies:
  python:
    - pypdftk==0.5
    - cairosvg
    - docx2pdf
    - locate